source.entsoe.jar = generated/generated/sources/annotationProcessor/java/test/,\
                    generated/generated/sources/annotationProcessor/java/main/,\
                    src/,\
                    test/
bin.includes = META-INF/,\
               marcin/.m2/repository/org/osgi/org.osgi.service.metatype/1.4.1/org.osgi.service.metatype-1.4.1.jar,\
               marcin/ws-mag/openems/io.openems.common/generated/io.openems.common.jar,\
               marcin/.m2/repository/com/google/guava/failureaccess/1.0.3/failureaccess-1.0.3.jar,\
               marcin/.m2/repository/org/osgi/org.osgi.util.promise/1.2.0/org.osgi.util.promise-1.2.0.jar,\
               marcin/.m2/repository/com/google/code/gson/gson/2.13.0/gson-2.13.0.jar,\
               marcin/.m2/repository/org/osgi/org.osgi.service.event/1.4.1/org.osgi.service.event-1.4.1.jar,\
               marcin/ws-mag/openems/io.openems.edge.timeofusetariff.api/generated/io.openems.edge.timeofusetariff.api.jar,\
               marcin/.m2/repository/org/osgi/org.osgi.service.cm/1.6.1/org.osgi.service.cm-1.6.1.jar,\
               marcin/.m2/repository/com/squareup/okio/okio-jvm/3.6.0/okio-jvm-3.6.0.jar,\
               marcin/ws-mag/openems/io.openems.edge.common/generated/io.openems.edge.common.jar,\
               marcin/.m2/repository/org/osgi/osgi.core/8.0.0/osgi.core-8.0.0.jar,\
               marcin/.m2/repository/org/ops4j/pax/logging/pax-logging-api/2.3.0/pax-logging-api-2.3.0.jar,\
               marcin/.m2/repository/org/osgi/org.osgi.service.component.annotations/1.5.1/org.osgi.service.component.annotations-1.5.1.jar,\
               marcin/.m2/repository/org/osgi/org.osgi.service.component/1.5.1/org.osgi.service.component-1.5.1.jar,\
               marcin/.m2/repository/org/osgi/osgi.annotation/8.1.0/osgi.annotation-8.1.0.jar,\
               marcin/ws-mag/openems/io.openems.wrapper/generated/io.openems.wrapper.okhttp.jar,\
               marcin/.m2/repository/org/jetbrains/kotlin/kotlin-osgi-bundle/2.1.20/kotlin-osgi-bundle-2.1.20.jar,\
               marcin/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar,\
               marcin/.m2/repository/org/apache/servicemix/bundles/org.apache.servicemix.bundles.junit/4.13.2_1/org.apache.servicemix.bundles.junit-4.13.2_1.jar,\
               entsoe.jar
